elasticsearch:
  host: 'http://54.72.179.212'
  port: 9200

mock_api:
  host: 'http://localhost'
  port: 6666

geolocation:
  cache_size: 1000
  cache_file: '/tmp/ip_location_cache.yml'
  cache_dump_interval: 60

